name: Deploy PR to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master # Fallback for old branches

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

# Allow only one concurrent deployment per PR
concurrency:
  group: "pages-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state != 'closed'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: pnpm install

      - name: Update Next.js config with branch name
        run: |
          sed -i 's|basePath: "/tip-of-the-week"|basePath: "/tip-of-the-week/${{ github.head_ref }}"|' next.config.mjs
          sed -i 's|assetPrefix: ""|assetPrefix: "/tip-of-the-week/${{ github.head_ref }}"|' next.config.mjs

      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.state != 'closed'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `https://alteos-gmbh.github.io/tip-of-the-week/${context.payload.pull_request.head.ref}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployed to: ${url}`
            });

  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'closed'
    steps:
      - name: Delete branch deployment
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages-${{ github.head_ref }}
